# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up premake and add to path
        uses: abel0b/setup-premake@v1
      - name: setup libcurl
        run: |
            sudo apt-get update
            sudo apt-get install libcurl4-openssl-dev
      - name: configure
        run: premake5 gmake2
      - name: build
        run: make config=release -j
        
  windows-build:
    # This is for windows
    runs-on: windows-2019

    # Specific steps
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up premake and add to path
        uses: abel0b/setup-premake@v1
      - name: build curl
        shell: cmd
        run: |
          set VSLOCATION=C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\
          call %VSLOCATION%\VC\Auxiliary\Build\vcvarsall.bat x64
          cd external\curl
          call buildconf.bat
          cd winbuild
          %VSLOCATION%\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\nmake /f Makefile.vc mode=static MACHINE=x64 ENABLE_UNICODE=yes
      - name: configure
        run: premake5 vs2019
      - name: build
        run: |
          set VSLOCATION=C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\
          %VSLOCATION%\MSBuild\Current\Bin\MSbuild -m build/random-wallpaper.vcxproj -property:Configuration=Release

