# This is a basic workflow to help you get started with Actions

name: windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is for windows
  windows-build:
    runs-on: windows-2019

    # Specific steps
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
      - name: Cache dependencies
        uses: actions/cache@v2
        id: libcache
        with:
          path: |
            D:\gtest
            D:\cmake
          key: ${{ runner.os }}
      - name: Build cURL
        if: steps.libcache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
            cd external\curl && mkdir builds && cd builds
            cmake -A x64 -DBUILD_SHARED_LIBS=OFF -DCURL_STATIC_CRT=ON -DENABLE_UNICODE=ON -DCURL_WINDOWS_SSPI=ON -DCMAKE_USE_SCHANNEL=ON ..
            cmake --build . --config Release
            mkdir D:\cmake
            copy /y lib\Release\libcurl.lib D:\cmake
      - name: Copy cURL
        if: steps.libcache.outputs.cache-hit == 'true'
        shell: cmd
        run: |
          mkdir external\curl\builds\lib\Release
          copy D:\cmake\libcurl.lib external\curl\builds\lib\Release
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install gtest
        if: steps.libcache.outputs.cache-hit != 'true'
        uses: MarkusJx/googletest-installer@v1.1
      - name: Add Developer utils
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Setup premake
        uses: abel0b/setup-premake@8463d9a3b900273c6863825a886aaa3a129f7db6
      - name: Configure and Build
        run: |
          premake5 vs2019
          msbuild -p:Configuration=Release build/random-wallpaper.sln
      - name: Run tests
        run: |
            ./build/bin/Release/tests
          
