# This is a basic workflow to help you get started with Actions

name: windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is for windows
  windows-build:
    runs-on: windows-2019

    # Specific steps
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
      - name: Build cURL
        shell: cmd
        run: |
            cd external\curl && mkdir builds && cd builds
            cmake -A x64 -DBUILD_SHARED_LIBS=OFF -DCURL_STATIC_CRT=ON -DENABLE_UNICODE=ON ..
            cmake --build . --config Release
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        # By default, this installs a Release version
        # For local debug builds, build gtest in Debug mode
      - name: Install gtest
        uses: MarkusJx/googletest-installer@v1.1
      - name: Configure and Build
        run: |
          premake5 vs2019
          msbuild -p:Configuration=Release build/random-wallpaper.sln
      - name: Run tests
        run: |
            ./build/bin/Release/tests
          
