# This is a basic workflow to help you get started with Actions

name: windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is for windows
  windows-build:
    runs-on: windows-2019

    # Specific steps
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up premake and add to path
        uses: abel0b/setup-premake@v1
      - name: configure curl
        shell: cmd
        run: |
          cd external\curl
          call buildconf.bat
      - name: build curl x64
        uses: ilammy/msvc-dev-cmd@v1
        with: 
          arch: x64
      - run: |
          cd external\curl\winbuild
          nmake /f Makefile.vc mode=static MACHINE=x64 ENABLE_UNICODE=yes
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install gtest
        uses: MarkusJx/googletest-installer@v1.1
      - name: configure and build
        run: |
          premake5 vs2019
          msbuild -p:Configuration=Release build/random-wallpaper.sln
      - name: test      
        run: |
            ./build/bin/Release/tests
          
